name: Pipeline de Testes Automatizado - Lista de Tarefas

on: 
  push:
    branches:
        - main
    pull_request:
      branches:
        - main
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v3

    - name: Configurar Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'

    - name: Instalar Dependências
      run: npm install
    
    - name: Instalar Jest globalmente
      run: npm install -g jest

    - name: Executar Testes
      run: npm run test

  